### ISSUE TITLE
Offsetting polygons doesn't work as intended

### ISSUE THREAD

**Issue by zhaishengfu** [Xrayez/godot-clipper#1]
Thanks for the sharing. i have a problem when using offset, below is my code
	clipper.set_mode(Clipper.MODE_OFFSET)
	clipper.set_join_type(Clipper.kRound)
	clipper.add_points(c[0])
	clipper.offset(c[0], 100.0)
	clipper.execute()
and c[0] is my image countour, the result is the same as the countour and do not have the effect of clipperoffset. what's wrong?

**Comment by Xrayez** [comment]
There are two ways you can do this, the first one is as you initially started doing it:
```gdscript
clipper.set_mode(Clipper.MODE_OFFSET)
clipper.set_join_type(Clipper.kRound)
clipper.delta = 100.0 # don't forget to set offset amount
clipper.add_points(c[0])
clipper.execute()
var contour = clipper.get_solution(0)
```
Another quick way of simplifying all above:
```gdscript
clipper.set_join_type(Clipper.kRound)
var contour = clipper.offset(c[0], 100.0)
```

The main difference between the two is that you can add multiple contours to clipper instance and perform a single offset operation on all of them simultaneously, *and* being able to offset the same paths but using different offset amount for each:

```gdscript
clipper.set_mode(Clipper.MODE_OFFSET)
clipper.set_join_type(Clipper.kRound)
clipper.add_points(c[0])
	
clipper.delta = 100.0
clipper.execute()
	
clipper.delta = 200.0
clipper.execute() # the result is the same as previous but with delta 200
```

The quick way allows you to not worry about all these intermediate steps.

**Comment by zhaishengfu** [comment]
sorry, but i failed . using the delta method, i can successfully offset one  contour
clipper.set_mode(Clipper.MODE_OFFSET)
	clipper.set_join_type(Clipper.kRound)
	
	clipper.add_points(c[0])
	
	clipper.delta = 10.0 # don't forget to set offset amount
	clipper.execute()
![image](https://user-images.githubusercontent.com/7630101/54805884-4ca13100-4cb3-11e9-82fe-2f6d16ba1715.png)

but when i use twice 
	clipper.set_mode(Clipper.MODE_OFFSET)
	clipper.set_join_type(Clipper.kRound)
	
	clipper.add_points(c[0])
	
	clipper.delta = 10.0 # don't forget to set offset amount
	clipper.execute()
	
	clipper.delta = 200.0 # don't forget to set offset amount
	clipper.execute()
only the latter 200 contour is successful
![image](https://user-images.githubusercontent.com/7630101/54805914-722e3a80-4cb3-11e9-9640-f4a1074d5cac.png)
do i misunderstand your meaning?

**Comment by Xrayez** [comment]
Yes, it won't reuse the result of the previous operation, but that way you can offset your *original* polygon multiple times to create many layers of the same contour, so this is expected.

If you want to offset the *result* again, you need to clear clipper, re-add contours that were previously offset, and apply the same offsetting again. Or simply use the convenience method `clipper.offset` again on your contour.

**Comment by zhaishengfu** [comment]
> Yes, it won't reuse the result of the previous operation, but that way you can offset your _original_ polygon multiple times to create many layers of the same contour, so this is expected.
> 
> If you want to offset the _result_ again, you need to clear clipper, re-add contours that were previously offset, and apply the same offsetting again. Or simply use the convenience method `clipper.offset` again on your contour.

**Comment by zhaishengfu** [comment]
ok， got it. thanks for your reply
