### ISSUE TITLE
Triangulation point order in clipping solution

### ISSUE THREAD

**Issue by zhaishengfu** [Xrayez/godot-clipper#3]
hello, what is the order of the points after MODE_TRIANGULATE ?, for example the points are
[a, b], [c, d], [e, f], [g, h],..
how can i get all the triangles using these points

**Comment by Xrayez** [comment]
The clipping solution resulting from triangulation consists of consecutive triangle points in one array, so it produces `[1, 2, 3, 4, 5, 6, ..., n]` where `n` is a multiple of 3, here's one of the ways to retrieve triangles:
https://github.com/Xrayez/godot-clipper/blob/857f9fb31b5bac109fb55e77cfa871acf58ae1a5/examples/projects/closed_paths/clipper.gd#L64-L71

**Comment by zhaishengfu** [comment]
Ok， Got it. and I find some examples you writed, thanks very much. and you answer questions promptly. enjoy your work

**Comment by zhaishengfu** [comment]
new question again.. when i use the polygon point to do triangulation, the result is ok
![image](https://user-images.githubusercontent.com/7630101/54889987-43e27200-4ee2-11e9-9e2e-7c34c1d329b8.png)
but when i add some points( the point in yellow color), the result is strange
![image](https://user-images.githubusercontent.com/7630101/54890019-72604d00-4ee2-11e9-980e-023ab9f1181d.png)
you can see that it automatically add some points as i marked in the following picture
![image](https://user-images.githubusercontent.com/7630101/54890077-9ae84700-4ee2-11e9-9e46-5086825af356.png)
and , i do not want the outer liens as i marked in the following picture
![image](https://user-images.githubusercontent.com/7630101/54890108-c4a16e00-4ee2-11e9-83c7-f0acece8a1da.png)

what is the reason of automacally adding points and do you think i can delete these outer lines?? are the orders of points important? my method is first get the contour and then append new points(yellow color) to the contour array. Is this right?

**Comment by Xrayez** [comment]
See my other comment regarding this:
https://github.com/godotengine/godot/pull/23559#issuecomment-447367142

The point order is important for triangulation. If you just append those points to the end of your contour, it will just treat it as a self-intersecting polygon, so triangulation will always be wrong.

I don't think there's a way to add internal vertices with clipper, but you could try to replace them with tiny holes consisting minimum of 3 points that should be in clockwise (?) order for the clipper to distinguish them as being holes, that way it should do triangulation without much issues. 

Not sure how it would impact the quality of what you're trying to achieve. If this is for mesh deformation, AFAIK it's already possible with Godot 3.1.

**Comment by zhaishengfu** [comment]
yes， i am using 3.1 and know how to use its internal mesh deformation. but i think it is not fit for my needs. AFAIK,  you can not use ik bone for the deformation because it only supports added bone, and godot ik bone is generated automaticlly and i do not know how to access them. i look the code and find that if i want to make ik in hand-added bone, the bone must have metadata"_edit_bone", and the process of add points by hand is time-consuming, so i want to generate them automatically.
 You can search "Unity Puppet2D"  to get better understand my meaning. Anyhow, you give me good advice and thank you for you kindness

**Comment by Xrayez** [comment]
Closing in favor of [GeometryTools](https://github.com/Xrayez/godot-geomtools) module. This module is also deprecated: dbf602a.
