### ISSUE TITLE
Mixed parent-child relationship between polygons while clipping

### ISSUE THREAD

**Issue by Jiaming00** [Xrayez/godot-clipper#4]
I changed the code in your closed polygon example to test the parent-child relationship between the polygons, but got some weird results. In the gif,i think the middle hole should always be in the hole state(Polygons in the list should be merged with each other,am i right ?), but it is not.
![](https://github.com/Jiaming00/lib0/raw/master/clipper-test.gif)
print info , set the color of the holes to black
![](https://github.com/Jiaming00/lib0/raw/master/clipper_test_code_01.png)
build hierarchy
![](https://github.com/Jiaming00/lib0/raw/master/clipper_test_code_02.png)
add code to process
![](https://github.com/Jiaming00/lib0/raw/master/clipper_test_code_03.png)

**Comment by Xrayez** [comment]
Thanks for reporting, I've never actually tested hierarchy thoroughly so it may certainly be a bug with the module, but I've experienced this with the new Clipper version (10.0.0) specifically which didn't happen in 6.4.2, even without using PolyTree structure, so not sure. Is the bug consistent if you redraw it slightly different?

It may also depend on how you feed the clipped output back as input, so at some point it may happen that polygon orientation gets flipped which turns a hole into a solid object.

If you can provide a reproduction project here (just drag and drop the zipped godot project), I could probably investigate this further more quickly.

**Comment by Jiaming00** [comment]
If redraw means to repeat the operation as shown in the gif, then I can confirm that the results are consistent
[closed_paths.zip](https://github.com/Xrayez/godot-clipper/files/4014279/closed_paths.zip)
![clipper-test-2](https://user-images.githubusercontent.com/29698949/71643798-d6793280-2cf8-11ea-8a86-4e209abbccfd.gif)

**Comment by Jiaming00** [comment]
Sorry, the previous fill color is not very accurate, because I changed the alpha to 0.5, the normal one should be:
[closed_paths.zip](https://github.com/Xrayez/godot-clipper/files/4014303/closed_paths.zip)
![clipper-test-3](https://user-images.githubusercontent.com/29698949/71644004-4d63fa80-2cfc-11ea-9411-873f4bb52b7b.gif)

**Comment by Jiaming00** [comment]
If redraw means to repeat the operation as shown in the gif, then I can confirm that the results are consistent

**Comment by Xrayez** [comment]
I've experimented with drawing polylines to represent polygons instead for more visual clarity as the order of contours is not deterministic which can interfere with drawing (white is boundary, color is holes):

![clipper-donut-polylines](https://user-images.githubusercontent.com/17108460/71644544-c3ec0280-2cd2-11ea-9e21-cd9edc4cfb8a.png)

[closed_paths.zip](https://github.com/Xrayez/godot-clipper/files/4014429/closed_paths.zip)

The inner white polygon might be actually another independent polygon which can be treated as an object sitting "on top" of the polygon with a hole, even if it's not inside it. The hierarchy array shows that the inner white polygon returns `[0]` which indicates that it's a topmost polygon which just happens to reside in the area of the first polygon with a hole (this should return `-1` maybe) I think it's just one of those cases of visual discontinuity when we attempt to "draw" polygons like that but without a clear distinction I'm not sure what has to be fixed.

In rare cases, triangulation of complex shapes may also fail occasionally when drawing so you'll want to use `clipper.triangulate` instead and draw the shapes with a more low-level interface provided by the `VisualServer.canvas_item_add_triangle_array`.

**Comment by Jiaming00** [comment]
My point is that for a group of polygons, there must be only one polygon at the top. If an independent polygon1 is inside another polygon2, but not inside polygon2's hole, this is completely meaningless,because they are in the same world.
What I mean is that a sub-polygon of a polygon must be a hole, and a sub-polygon of a hole must be a polygon.
In fact, if you draw the following multi-layer inclusions, you can see it does work like this, so I think this should be a bug。
![clipper_test_5](https://user-images.githubusercontent.com/29698949/71645402-e00f9400-2d12-11ea-90ac-6db57e583a59.png)
![clipper_test_6](https://user-images.githubusercontent.com/29698949/71645407-f158a080-2d12-11ea-8339-d8ec397496fe.png)

I just found another way to reproduce this situation:
![clipper-test-4](https://user-images.githubusercontent.com/29698949/71645315-78a51480-2d11-11ea-84e0-80092df9783a.gif)
 I need to generate ouline in the program I am developing, so I need to perform the offset operation, so this weird phenomenon will affect this operation. Although Geomtry.clip_polygon_2d can be used to determine the inclusion relationship, but I think this is redundant

**Comment by Xrayez** [comment]
I've narrowed down the problem as well. Compare:

```gdscript
if clipper.is_hole(i):
	color = Color(randf(), randf(), randf())*Color(0.5,0.5,0.5,1.0)
```
```gdscript
if Geometry.is_polygon_clockwise(poly): # if clockwise, it's a hole
	color = Color(randf(), randf(), randf())*Color(0.5,0.5,0.5,1.0)
```

With the second snippet it draws those holes just fine. So, either I messed something up with hierarchy indices or it might be Clipper's internal bug, because `is_hole` is just a wrapper for `Clipper.IsHole` method which acts upon internally populated `PolyTree` structure.

Iterating over the solution might not be a feasible way to draw those outlines for you, that's why there's `get_hierarchy` method which returns indices to parent and children polygons pointing to solution (or more high-level methods such as `get_children`). Index parity should in theory determine whether a polygon is a boundary or a hole.

**Comment by Xrayez** [comment]
@Jiaming00 I've created [GeometryTools](https://github.com/Xrayez/godot-geomtools) module in which you can do hierarchy of polygons with:

```gdscript
var solution = GeometryTools2D.polygons_boolean_tree(polygons_subject, with_polygons)
```

The traversal of the tree can be done similarly to this:
```gdscript
if solution is PolyNode2D:
	var nodes = [solution]
	while not nodes.empty():
		var node = nodes.back()
		nodes.pop_back()

		if node.path.size() > 0:
			draw_colored_polygon(node.path, c)

		for child in node.get_children():
			nodes.push_back(child)
```
This is more or less documented within built-in docs once you compile the module, cheers!

You can also switch between Clipper 6.4.2 and Clipper 10.0.0 backends in the project settings and see if that makes a difference for you.

I'm also deprecating `godot-clipper`: dbf602a.
